# Webots Tiago RTAB-Map parameters. This file is owned by this deployment.
RGBD/CreateOccupancyGrid: true
Grid/RangeMax: 6.0
Grid/CellSize: 0.05
Grid/RayTracing: true # when set to false, ghost points will exist on map - wheatfox 2026.7.19
Grid/3D: false
Grid/NormalsSegmentation: false
Grid/MaxObstacleHeight: 1.0
Grid/MaxGroundHeight: 0.1
Reg/Strategy: 1
Reg/Force3DoF: true
Optimizer/Strategy: 1
RGBD/NeighborLinkRefining: true
RGBD/ProximityBySpace: true
RGBD/AngularUpdate: 0.05
RGBD/LinearUpdate: 0.05
Mem/NotLinkedNodesKept: false
Vis/MinInliers: 12
Rtabmap/DetectionRate: 5.0
Icp/MaxCorrespondenceDistance: 0.2
Icp/MaxTranslation: 0.5
Icp/MaxRotation: 0.78
