#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0
#
# Generate Python protobuf stubs for packages that execute inside the Webots
# container.  Code generated by a newer protobuf major cannot be imported by
# an older runtime, so using whichever grpcio-tools happens to be active on the
# host is not reproducible.  Keep the generator aligned with the versions
# installed by sim/bridge/Dockerfile and share one venv across the local Tiago
# packages.
set -euo pipefail

if [[ "$#" -lt 1 ]]; then
    echo "usage: $0 <package-root> [rbnx-codegen-args...]" >&2
    exit 2
fi

PKG="$(cd "$1" && pwd)"
shift
WEBOTS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENV="$WEBOTS_ROOT/rbnx-boot/python-codegen-venv"
PROTOBUF_VERSION="6.33.6"
GRPC_TOOLS_VERSION="1.76.0"
GRPCIO_VERSION="1.78.0"

if ! command -v uv >/dev/null 2>&1; then
    echo "[webots/codegen] error: 'uv' not found on PATH. Install: https://docs.astral.sh/uv/" >&2
    exit 1
fi

compatible=0
if [[ -x "$VENV/bin/python" ]]; then
    if "$VENV/bin/python" - "$PROTOBUF_VERSION" "$GRPC_TOOLS_VERSION" "$GRPCIO_VERSION" <<'PY'
from importlib.metadata import version
import sys

expected_protobuf, expected_tools, expected_grpc = sys.argv[1:]
if version("protobuf") != expected_protobuf:
    raise SystemExit(1)
if version("grpcio-tools") != expected_tools:
    raise SystemExit(1)
if version("grpcio") != expected_grpc:
    raise SystemExit(1)
PY
    then
        compatible=1
    fi
fi

if [[ "$compatible" != "1" ]]; then
    echo "[webots/codegen] preparing protobuf $PROTOBUF_VERSION / grpcio-tools $GRPC_TOOLS_VERSION"
    rm -rf "$VENV"
    uv venv "$VENV"
    uv pip install --python "$VENV/bin/python" \
        "protobuf==$PROTOBUF_VERSION" \
        "grpcio-tools==$GRPC_TOOLS_VERSION" \
        "grpcio==$GRPCIO_VERSION"
fi

echo "[webots/codegen] rbnx codegen -p $PKG $*"
RBNX_CODEGEN_PYTHON="$VENV/bin/python" \
    PATH="$VENV/bin:$PATH" \
    rbnx codegen -p "$PKG" "$@"

CODEGEN_ROOT="$PKG/rbnx-build/codegen"
PYTHONPATH="$CODEGEN_ROOT/proto_gen:$CODEGEN_ROOT/robonix_mcp_types:${PYTHONPATH:-}" \
    "$VENV/bin/python" - "$CODEGEN_ROOT" <<'PY'
import importlib
import pkgutil
from pathlib import Path
import sys

codegen_root = Path(sys.argv[1])
module_dirs = [codegen_root / "proto_gen", codegen_root / "robonix_mcp_types"]
modules = sorted(
    {
        module.name
        for module_dir in module_dirs
        if module_dir.is_dir()
        for module in pkgutil.iter_modules([str(module_dir)])
        if module.name.endswith(("_pb2", "_pb2_grpc", "_mcp"))
    }
)
if not modules:
    raise RuntimeError(f"no generated Python modules found below {codegen_root}")
for module in modules:
    importlib.import_module(module)
print(f"[webots/codegen] generated import smoke OK ({len(modules)} modules)")
PY
